<svelte:head>
	<title>Terms of Service — MyPhoto3D</title>
	<meta name="description" content="Terms of Service for MyPhoto3D." />
</svelte:head>

<div class="page">
	<div class="container">

		<div class="doc-header">
			<p class="eyebrow">Legal</p>
			<h1>Terms of Service</h1>
			<p class="last-updated">Last updated: March 22, 2026</p>
		</div>

		<div class="doc-body">

			<section>
				<h2>1. Agreement</h2>
				<p>
					By purchasing a license or using MyPhoto3D ("the Service"), you agree to be bound by
					these Terms of Service ("Terms"). The Service is operated by Parker Drouillard, an
					individual operating in Ontario, Canada ("we," "us," or "our"). If you do not agree to
					these Terms, do not use the Service.
				</p>
			</section>

			<section>
				<h2>2. Eligibility</h2>
				<p>
					You must be at least 18 years of age to purchase or use the Service. By using the
					Service, you represent and warrant that you are 18 years of age or older.
				</p>
			</section>

			<section>
				<h2>3. License</h2>
				<p>
					Upon purchasing a lifetime license, we grant you a personal, non-exclusive,
					non-transferable right to access and use the Service. Your license is tied to your
					account and may not be sold, transferred, or shared with any other person.
				</p>
			</section>

			<section>
				<h2>4. Acceptable Use</h2>
				<p>
					You may use the STL files generated by the Service for any lawful purpose, including
					personal and commercial use such as selling printed items. You may not use the Service
					to process images you do not own or have the right to use, or to generate content that
					is illegal, obscene, or infringes the intellectual property rights of others. We
					reserve the right to suspend or terminate your access if we determine, at our sole
					discretion, that your use of the Service is unreasonable or abusive.
				</p>
			</section>
            
            <section>
                <h2>4b. Prohibited Content</h2>
                <p>You may not upload photos or use the Service to generate STL files that depict or reproduce:</p>
                <ul>
                    <li>
                        Any person under the age of 18 in a sexual or exploitative context. We are
                        legally required to report any suspected child sexual abuse material (CSAM)
                        to the Canadian Centre for Child Protection at
                        <a href="https://www.cybertip.ca" target="_blank" rel="noopener noreferrer">Cybertip.ca</a>
                        and to relevant law enforcement authorities
                    </li>
                    <li>
                        Intimate or sexually explicit images of any identifiable person without
                        their documented consent
                    </li>
                    <li>
                        Identifiable individuals — including public figures, celebrities, or any
                        third party — where the resulting printed item would be used for commercial
                        purposes without that person's consent
                    </li>
                    <li>
                        Copyrighted characters, trademarked logos, or other intellectual property
                        you do not have the right to reproduce commercially
                    </li>
                    <li>
                        Content that promotes, glorifies, or facilitates violence, hatred, or
                        discrimination against any person or group
                    </li>
                </ul>
                <p>
                    We reserve the right to refuse, remove, or report any content that we believe
                    violates these prohibitions, and to suspend or permanently terminate the account
                    of any user who submits prohibited content. Violation of the CSAM prohibition
                    will be reported to authorities without notice.
                </p>
            </section>

			<section>
				<h2>5. Photo Uploads and Intellectual Property</h2>
				<p>By uploading photos to the Service, you represent and warrant that:</p>
				<ul>
					<li>
						You are the owner of the photos, or you have obtained all necessary rights,
						licences, and permissions from the rights holder to use the photos in connection
						with the Service;
					</li>
					<li>
						Your upload does not infringe the intellectual property, privacy, or publicity
						rights of any third party; and
					</li>
					<li>
						You grant Parker Drouillard a limited, non-exclusive, royalty-free licence to use,
						process, and reproduce the uploaded photos solely for the purpose of generating
						your requested STL file. This licence terminates when your photos are deleted from
						our servers, which occurs within 24 hours of your order being processed.
					</li>
				</ul>
				<p>
					We are not responsible for any claims arising from photos you upload in violation of
					these terms. If we receive a valid intellectual property complaint regarding your
					uploaded content, we reserve the right to suspend your access pending resolution.
				</p>
			</section>

			<section>
				<h2>6. Fair Use</h2>
				<p>
					The Service operates under a fair use policy. We do not publicly disclose specific
					generation limits, but we reserve the right to restrict or suspend access for any
					account that we determine, at our sole discretion, is using the Service in a manner
					inconsistent with reasonable personal or small business use. We will make reasonable
					efforts to notify you before taking such action.
				</p>
			</section>

			<section>
				<h2>7. Payments and Refunds</h2>
				<p>
					All purchases are final. We do not offer refunds under any circumstances. By
					completing a purchase, you acknowledge that you have read these Terms and understand
					that the payment is non-refundable. Licenses are priced in Canadian dollars (CAD) and
					processed securely through Square.
				</p>
			</section>

			<section>
				<h2>8. Privacy</h2>
				<p>
					Your use of the Service is also governed by our Privacy Policy, which is incorporated
					into these Terms by reference. Photos you upload are deleted from our servers within
					24 hours of your order being processed. We do not sell your personal information to
					third parties.
				</p>
			</section>

			<section>
				<h2>9. Intellectual Property</h2>
				<p>
					You retain all rights to the photos you upload. You own the STL files generated from
					your photos. We retain all rights to the Service itself, including its software,
					design, and underlying systems.
				</p>
			</section>

			<section>
				<h2>10. Disclaimer of Warranties</h2>
				<p>
					The Service is provided "as is" and "as available" without warranties of any kind,
					either express or implied. We do not warrant that the Service will be uninterrupted,
					error-free, or that the generated STL files will meet your specific requirements.
				</p>
			</section>

			<section>
				<h2>11. Limitation of Liability</h2>
				<p>
					To the maximum extent permitted by applicable law, Parker Drouillard shall not be
					liable for any indirect, incidental, special, consequential, or punitive damages
					arising out of or related to your use of the Service, even if advised of the
					possibility of such damages. Our total liability to you for any claim arising out of
					or related to these Terms shall not exceed the amount you paid for your license.
				</p>
			</section>

			<section>
				<h2>12. Governing Law</h2>
				<p>
					These Terms are governed by the laws of the Province of Ontario and the federal laws
					of Canada applicable therein. Any disputes arising under these Terms shall be subject
					to the exclusive jurisdiction of the courts of Ontario.
				</p>
			</section>

			<section>
				<h2>13. Changes to These Terms</h2>
				<p>
					We reserve the right to modify these Terms at any time. We will notify you of
					material changes by posting the updated Terms on this page with a revised date. Your
					continued use of the Service after such changes constitutes your acceptance of the
					new Terms.
				</p>
			</section>

			<section>
				<h2>14. Contact</h2>
				<p>
					For any questions regarding these Terms, please contact us at
					<a href="mailto:support@myphoto3d.com">support@myphoto3d.com</a>.
				</p>
			</section>

		</div>
	</div>
</div>

<style>
	.page {
		padding: 4rem 0 6rem;
	}

	.container {
		max-width: 720px;
		margin: 0 auto;
		padding: 0 2.5rem;
	}

	/* ── Header ── */
	.doc-header {
		margin-bottom: 3rem;
		padding-bottom: 2rem;
		border-bottom: 1px solid var(--rule);
	}

	.eyebrow {
		font-size: 0.6875rem;
		letter-spacing: 0.14em;
		text-transform: uppercase;
		color: var(--ink-light);
		margin-bottom: 0.75rem;
	}

	h1 {
		font-family: var(--serif);
		font-size: clamp(2rem, 3.5vw, 2.875rem);
		line-height: 1.08;
		letter-spacing: -0.025em;
		margin-bottom: 0.5rem;
	}

	.last-updated {
		font-size: 0.8125rem;
		color: var(--ink-light);
	}

	/* ── Body ── */
	.doc-body {
		display: flex;
		flex-direction: column;
		gap: 2.5rem;
	}

	section h2 {
		font-family: var(--serif);
		font-size: 1.125rem;
		font-weight: 400;
		letter-spacing: -0.01em;
		margin-bottom: 0.75rem;
		color: var(--ink);
	}

	section p {
		font-size: 0.9375rem;
		color: var(--ink-mid);
		line-height: 1.75;
		margin-bottom: 0.75rem;
	}

	section p:last-child {
		margin-bottom: 0;
	}

	section ul {
		margin: 0.75rem 0 0.75rem 1.25rem;
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}

	section ul li {
		font-size: 0.9375rem;
		color: var(--ink-mid);
		line-height: 1.7;
	}

	section a {
		color: var(--ink);
		text-decoration: underline;
		text-underline-offset: 2px;
	}

	section a:hover {
		color: var(--accent);
	}

	@media (max-width: 860px) {
		.page {
			padding: 2.5rem 0 4rem;
		}
	}
</style>